### ISSUE TITLE
Opening files with spaces in their names

### ISSUE THREAD

**Issue by Flurrywinde** [wsdjeg/FlyGrep.vim#3]
If I use FlyGrep to try and open a file with spaces in its name, I get the following error:

```
Error detected while processing function FlyGrep#open[9]..13[5]..15[4]..<SNR>79_open_
item:
line   11:
E447: Can't find file "./[First word of filename]" in path
```
Then, after this, the cursor is invisible.

**Comment by wsdjeg** [comment]
cursor is hidden when it is at the end. move cursor by `<Left>` you will see it.

**Comment by Flurrywinde** [comment]
Hitting the left arrow doesn't help. The cursor even remains invisible if I exit vim and go back to the terminal. It reappears if I run vim again, but I can enter terminal commands like `clear`, `ls`, etc with the cursor invisible.

Also, the main problem isn't the cursor disappearing but the error upon trying to open files with spaces in their name. Probably the cursor would not disappear to begin with if this bug were fixed, but I thought it would still be good to figure out why the cursor becomes invisible.
